spring:
  datasource:
    url: jdbc:h2:mem:RM
    username: sa
    password: pwd
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  h2:
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false

security.jwt.token.secret-key: abcd1234
